const checkEmailWallet = require('./account/checkEmailWallet')
const getLastFiveBookings = require('./wallet/getLastFiveBookings')
const maxAmtCalc = require('./wallet/maxAmtCalc')
const setTwoNumberDecimal = require('./wallet/setTwoNumberDecimal')
const topUpWalletPage = require('./wallet/topUpWalletPage')
const walletHomePage = require('./wallet/walletHomePage')
const cashOut = require('./wallet/cashOut')
const submitCashOut = require('./wallet/submitCashOut')